tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_boundary
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2020_11_24_dublin_boundary.gpkg
    product: data/external/2020_11_24_dublin_boundary.gpkg

  - source: codema_dev_tasks.requests.fetch_file
    name: download_nta_2016_links
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_09_23_nta_road_transport_emission_links_2016.zip
    product: data/external/2021_09_23_nta_road_transport_emission_links_2016.zip
 