on_render: hooks.load_environmental_variables
tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_buildings
    params:
      url: s3://codema-dev/dublin_census_2016_filled_with_ber_public_14_05_2021.parquet
    product: data/external/dublin_census_2016_filled_with_ber_public_14_05_2021.parquet
  - source: codema_dev_tasks.requests.fetch_file
    name: download_small_area_boundaries
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg
  - source: tasks.calculate_small_area_heat_pump_viability
    product: data/processed/small_area_heat_pump_viability.csv
  - source: map_heat_pump_viability.py
    product:
      nb: data/notebooks/map_heat_pump_viability.ipynb
      gpkg: data/processed/small_area_heat_pump_viability.gpkg
      html: data/processed/small_area_heat_pump_viability.html
