tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_esb_substation_capacities
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/heatmap-download-version-nov-2020.csv
    product: data/external/heatmap-download-version-nov-2020.csv
  
  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_small_area_boundaries
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg

  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_mv_index_ids
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/esb_20210107_dublin_mv_index.csv
    product: data/external/esb_20210107_dublin_mv_index.csv

  - source: codema_dev_tasks.contracts.check_file_exists
    name: check_electricity_grid_cad_data_exists
    params:
      filepath: data/raw/ESBdata_20210107
    product: data/raw/ESBdata_20210107

  - source: tasks.extract_dublin_substations
    product: data/processed/dublin-heatmap-download-version-nov-2020.gpkg

  - source: link_lv_substations_to_electoral_districts.py
    product:
      nb: data/notebooks/link_lv_substations_to_electoral_districts.ipynb
      csv: data/processed/lv_substations_in_electoral_districts.csv
      gpkg: data/processed/electoral_district_lv_capacities.gpkg
  
  - source: tasks.extract_dublin_mv_and_lv_network
    product: data/processed/dublin_mv_and_lv_network.gpkg

  - source: tasks.extract_network_lines
    product: data/processed/dublin_mv_and_lv_network_lines.gpkg
    
  - source: cluster_lv_substations.py
    product:
      nb: data/notebooks/cluster_lv_substations.ipynb
      gpkg: data/processed/lv_substation_clusters.gpkg