name: electricity-grid
channels:
  - conda-forge
dependencies:
  - ploomber
  - geopandas
  - ipykernel
  - scikit-learn
  - poetry
  
  - pip
  - pip:
    - git+https://github.com/codema-dev/tasks
    - .