tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_esb_substation_capacities
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/heatmap-download-version-nov-2020.csv
    product: data/external/heatmap-download-version-nov-2020.csv
  
  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_small_area_boundaries
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg

  - source: link_lv_substations_to_electoral_districts.py
    product:
      nb: data/notebooks/link_lv_substations_to_electoral_districts.ipynb
      csv: data/processed/lv_substations_in_electoral_districts.csv
      gpkg: data/processed/electoral_district_lv_capacities.gpkg